server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/Documents/config
        git:
#          uri: file://Users/kimjunseo/Documents/config
          uri: https://github.com/wnstj1548/spring-cloud-config
          default-label: master
#          username:
#          password:
#  profiles:
#    active: native
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
