server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/config
        git:
#          uri: file://Users/kimjunseo/Documents/config
          uri: https://github.com/wnstj1548/spring-cloud-config
#          username:
#          password:
  profiles:
    active: native
